nome = input ("Insira o nome: ")
nacionalidade = input ("Insira a nacionalidade: ")
estado_civil = input ("Insira o estado civil: ")
profissão = input ("Insira a profissão: ")
rg = input ("Insira o rg CIRG: ")
expedidor = input ("Insira o órgão expedidor: ")
cpf = input ("Insira o cpf: ")
endereço = input ("Insira o endereço: ")
endereço_nome = input ("Insira o nome do endereço: ")
nome1 = input ("Insira o segundo nome: ")
nacionalidade1 = input ("Insira a segunda nacionalidade: ")
estado_civil1 = input ("Insira o segundo estado civil: ")
profissão1 = input ("Insira a segunda profissão: ")
rg1 = input ("Insira o segundo rg CIRG: ")
expedidor1 = input ("Insira o segundo órgão expedidor: ")
cpf1 = input ("Insira o segundo cpf: ")
endereço1 = input ("Insira o segundo endereço: ")

print (nome, nacionalidade, estado_civil, profissão, rg, expedidor, cpf, endereço, endereço_nome, nome1, nacionalidade1, estado_civil1, profissão1, rg1, expedidor1, cpf1, endereço1)